// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DictionaryContext))]
    [Migration("20221208183938_UsersAdded")]
    partial class UsersAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("DAL.Models.PartOfSpeech", b =>
                {
                    b.Property<int>("PartOfSpeechId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartOfSpeechId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PartOfSpeechId");

                    b.ToTable("PartOfSpeeches");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserADId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DAL.Models.Word", b =>
                {
                    b.Property<int>("WordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("InPolish")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("InWarmian")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("PartOfSpeechId")
                        .HasColumnType("int");

                    b.HasKey("WordId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PartOfSpeechId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("DAL.Models.WordGroup", b =>
                {
                    b.Property<int>("WordGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WordGroupId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserADId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WordGroupId");

                    b.HasIndex("UserADId");

                    b.ToTable("WordGroup", (string)null);
                });

            modelBuilder.Entity("WordWordGroup", b =>
                {
                    b.Property<int>("WordGroupsWordGroupId")
                        .HasColumnType("int");

                    b.Property<int>("WordsWordId")
                        .HasColumnType("int");

                    b.HasKey("WordGroupsWordGroupId", "WordsWordId");

                    b.HasIndex("WordsWordId");

                    b.ToTable("WordWordGroup");
                });

            modelBuilder.Entity("DAL.Models.Word", b =>
                {
                    b.HasOne("DAL.Models.Author", "Author")
                        .WithMany("Words")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.PartOfSpeech", "PartOfSpeech")
                        .WithMany("Words")
                        .HasForeignKey("PartOfSpeechId");

                    b.Navigation("Author");

                    b.Navigation("PartOfSpeech");
                });

            modelBuilder.Entity("DAL.Models.WordGroup", b =>
                {
                    b.HasOne("DAL.Models.User", "User")
                        .WithMany("WordGroups")
                        .HasForeignKey("UserADId")
                        .HasPrincipalKey("UserADId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WordWordGroup", b =>
                {
                    b.HasOne("DAL.Models.WordGroup", null)
                        .WithMany()
                        .HasForeignKey("WordGroupsWordGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Word", null)
                        .WithMany()
                        .HasForeignKey("WordsWordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Models.Author", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("DAL.Models.PartOfSpeech", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("DAL.Models.User", b =>
                {
                    b.Navigation("WordGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
